# Dependencies
markdown:             redcarpet
redcarpet:
    extensions:       [with_toc_data]
highlighter:          pygments
#highlighter:          rouge

# Permalinks
permalink:            :title.html
relative_permalinks:  true

# Setup
title:              BelajarPrg
tagline:            'Belajar Programming !'
description:        'Suatu projek untuk memperkaya bahan berkenaan pembangunan perisian dan web dalam Bahasa Melayu.'
url:                http://belajar.github.io/programming/
baseurl:            'js'
paginate:           5
excerpt_separator:  '<!--more-->'

analytics:
    ga:             ''
disqus:             belajarprogramming

authors:
  kamalmustafa:
    name:           Kamal Mustafa
    short_bio:      Web developer di MARIMORE Inc. Banyak terlibat dalam pembangunan aplikasi web menggunakan Python/Django (server-side) dan sekarang cuba berjinak-jinak dengan teknologi client-side.
    full_bio_ms:    '<a name="Kamal Mustafa" href="http://my.linkedin.com/in/mk4ml" style="font-weight:bold;">Kamal Mustafa</a> Web developer di MARIMORE Inc. Banyak terlibat dalam pembangunan aplikasi web menggunakan Python/Django (server-side) dan sekarang cuba berjinak-jinak dengan teknologi client-side. Aktif menulis di blog peribadi <a href="http://k4ml.github.io/">ImportError</a> dan Twitter <a href="http://twitter.com/k4ml">@k4ml</a>.'
    full_bio_en:    '<a href="http://my.linkedin.com/in/mk4ml">Kamal Mustafa</a> is a Web Developer at MARIMORE Inc. Involved in web applications development using Python/Django (server-side) and now looking into client-side technologies. Actively sharing his thought at personal blog <a href="http://k4ml.github.io/">ImportError</a> and Twitter <a href="http://twitter.com/k4ml">@k4ml</a>.'
    gravatar:       dab3052b18c86b0884341d9c2c67a4f3
    pic:            http://m.c.lnkd.licdn.com/mpr/pub/image-Xi3rdNhL21LXnFhIZ9ai-2TuhAQVtL47Xi3e-Ut6hszrbxGYXi3eI8yLh7vHUjxRwIF7/mohd-kamal-mustafa.jpg
    disclaimer:     All writings here are his own and not necessarily represent his employer's positions, strategies or opinions.

collections:
  tips:
    output: true
